name: Periodic health check

    
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '*/2 * * * *'
    

on:
  push:
    branches:  [ main ]

  workflow_dispatch:
     
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: Say hello
      run:  echo "Hello World!"

       
