name: Periodic health check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/2 * * * *'
    
  workflow_dispatch:

jobs:
  health check:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
             node-version: '12.x'
        - name:  url-health-check
          uses: jtalk/url-health-check-action@v1.2
          with:
            # Check the following URLs one by one sequentially
            url: https://pokedex-samu.herokuapp.com/
