name: Deployment pipeline

on:
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:
  simple_deployment_pipeline:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
             node-version: '12.x'
        - name: npm install
          run: npm install
        - name: lint
          run: npm "eslint \"**/*.{js,jsx}\""
        - name: npm test
          run: npm run test
