name: Deployment pipeline

on:
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:
  simple_deployment_pipeline:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
             node-version: '12.x'
        - name: npm install
          working-directory: './full-stack-open-pokedex'
          run: npm install
        - name: cd
          run: cd full-stack-open-pokedex
        - name: dir
          run: ls 
        - name: lint
          working-directory: './full-stack-open-pokedex'
          run: npm run eslint
        - name: npm test
          run: npm run test
